### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Lev1t1cus** [Silenthal/PetitMIDI#2]
How do you use it? Sorry if that's a really dumb question.

**Comment by Silenthal** [comment]
No problem - once you start it up, the program has two parts: the editor on the bottom (where you type out the notes of whatever song to play), and the green play button on top (which plays out the song you type). The editor is pretty much the entire white space of the window, so you can't miss it. Use it as such:

1. Type a song. For instance, "edcdeeerdddreggredcdeeeeddedc" (without the quotes)
2. Click the play button at the top.

The readme has details on the types of notes and such that can be played, in case you need to check.

**Comment by Lev1t1cus** [comment]
How do you start it up? Is there an app I need to download first?

**Comment by Lev1t1cus** [comment]
thank you for responding btw
